EventBrite-master/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'events#index'

  get 'home/secret'

  resources :events
  resources :users 
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

EventBrite-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

EventBrite-master/app/models/attendance.rb
class Attendance < ApplicationRecord

	belongs_to :user
	belongs_to :event
	after_create :inscription_event_email
	validates :user_id, presence: true
	validates :event_id, presence: true


	def inscription_event_email
		UserMailer.inscription_event_email(self).deliver_now
	end
end

EventBrite-master/app/models/event.rb
class Event < ApplicationRecord

	has_many :attendances
	has_many :users, through: :attendances
	belongs_to :user

	validates :start_date, presence: true
	validate :test_start_date
	
	validates :duration, presence: true
	validate :modulo_duration

	validates :title, presence: true, length: { in: 1..140 }

	validates :description, presence: true, length: { in: 20..1000 }

	validates :price, presence: true, numericality: { only_integer: true }, numericality: { greater_than: 1, less_than_or_equal_to: 1000 }

	validates :location, presence: true

	def test_start_date
		if start_date.present? && start_date.to_date < Date.today
		   errors.add(:start_date, "can't be in the past")
		end
	end

	def modulo_duration
		if duration.present? && duration % 5 != 0
		   errors.add(:duration, "must be a multiple of 5")
    	end
	end
end

EventBrite-master/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :attendances
	has_many :events, through: :attendances
	
	after_create :welcome_send

	validates :email, presence: true

	validates :email, length: { minimum: 3 }

  	
  	def welcome_send

    	UserMailer.welcome_email(self).deliver_now
   
    end

end

EventBrite-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

EventBrite-master/app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
  
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

EventBrite-master/app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
	end

	def new
		@event = Event.new
	end

	def show
		@event = Event.find(params[:id])
	end
end

EventBrite-master/app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_action :authenticate_user!, only: [:secret]
	
  def index
  end

  def secret
  end
end

EventBrite-master/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

EventBrite-master/app/helpers/application_helper.rb
module ApplicationHelper
end

EventBrite-master/app/helpers/charges_helper.rb
module ChargesHelper
end

EventBrite-master/app/helpers/events_helper.rb
module EventsHelper
end

EventBrite-master/app/helpers/home_helper.rb
module HomeHelper
end

EventBrite-master/app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

EventBrite-master/app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <center>
    
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
          </center>
<% end %>

EventBrite-master/app/views/events/index.html.erb
<!-- Header -->
  <header id="head">
    <div class="container">
      <h2 class="display-5">Bienvenue sur Event After All!</h2>
        <h1 class="lead">codé avec le ***</h1>
        <h3 class="tagline">Bordeaux, on dit pain au chocolat</h3>
        <i class="fas fa-heart"></i>
      </div>
  </header>
  <!-- /Header -->

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          <p>Ti jeu de mot Even After All, Event After All. T'as vu... Allez viens, des petits events sympas. Meilleurs qu'à Bordeaux.</p>
          <p style="margin-bottom:20px;">
          <p><a class="btn btn-primary btn-lg" href="https://www.youtube.com/watch?v=rlarCLhzfoU" role="button">Une belle équipe &raquo;</a></p>
        </div>
      </div>
    
   <%  @events = Event.all %>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">
          <% @events.each do |event| %>
          <div class="col-md-4">
            <h2><%= event.title %></h2>
            <p><%= event.description %></p>
            <p><a class="btn btn-secondary" href="<%= event_path(event.id) %>" role="button">En savoir plus &raquo;</a></p>
          </div>
          <% end %>
        </div>

EventBrite-master/app/views/events/new.html.erb
<div class="card border-info m-5">
 <div class="card-header">
  <h1>Crée ton propre évènement !</h1>
  </div>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <div class="card-body text-info">
        <div class="form-group">
          <%= text_field_tag 'title', @event.title, class: "form-control", placeholder: "Le nom de ton event" %>
          <%= text_area_tag 'start_date', @event.start_date, class: "form-control", placeholder: "La date de ton event" %>
          <%= date_field(:event, :start_date) %>
          <%= text_area_tag 'duration', @event.duration, class: "form-control", placeholder: "La durée de ton event" %>
          <%= text_field_tag 'location', @event.location, class: "form-control", placeholder: "Le lieu de ton event" %>
          <%= text_area_tag 'description', @event.description, class: "form-control", placeholder: "Kessissipasse?" %>
          <%= text_field_tag 'price', @event.price, class: "form-control", placeholder: "Le prix de ton event" %>
          <br /> <br />

          <%= submit_tag "Ajouter mon évènement", class: "btn btn-info" %>
        <% end %>
      </div>
    </div>
</div>
    <% if @event.errors.any? %>
    <div class="alert alert-danger" role="alert">
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
    </div>
      <% end %>

EventBrite-master/app/views/events/show.html.erb
<div>
<%= @event.title %>
Date : <%= @event.start_date %><br>
Durée : <%= @event.duration %><br>
Lieu : <%= @event.location %><br>
Description : <%= @event.description %><br>
Tarif : <%= @event.price %><br>
</div>

<% if user_signed_in? %> 
<p><a class="btn btn-primary btn-lg" href="<%= new_charge_path %>" role="button">Participer et passer à la caisse &raquo;</a></p>   

<% else %> 
<p><a class="btn btn-primary btn-lg" href="<%= new_user_registration_path %>" role="button">S'inscrire &raquo;</a></p>   
<% end %>

EventBrite-master/app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>
    <li>
      Voici ton email : <%= current_user.email %>
    </li>
    <li>
      <%= link_to "Secret page", home_secret_path %>
    </li>
    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>
  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>
  <% end %>
</ul>

EventBrite-master/app/views/home/secret.html.erb
<h1>Home#secret</h1>
<p>Find me in app/views/home/secret.html.erb</p>

EventBrite-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EvenbriteProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://bootswatch.com/4/lux/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">EVENT AFTER ALL</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "CRÉER UN EVENT", new_event_path, :class => "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          MON COMPTE
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Voir mon profil", current_user, :class => "dropdown-item" %>
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, :class => "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          S'INSCRIRE/SE CONNECTER
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Se connecter", new_user_session_path, :class => "dropdown-item" %>
          <%= link_to "S'inscrire", new_user_registration_path, :class => "dropdown-item" %>
        </div>
      </li>
      <% end %>

    </ul>
  </div>
</nav>

    <%= yield %>
    
    <p style="margin-bottom:150px;">

      <footer id="footer" class="top-space">

    <div class="footer1">
      <div class="container">
        <div class="row">
          
          <div class="col-md-3 widget">
            <h3 class="widget-title">Contact</h3>
            <div class="widget-body">
              <p>On est sur le Slack!<br>
                Jonathan Gaultier (Joongau sur slack) <br>
                Rémi Auzou (pas de pseudo pour monsieur) <br>
                Dylan Langlois-Hérault (Dylan LH sur slack) <br>
                Cyrille Amaro (Howok sur slack) <br>
                Armand Duval (Urbain4 sur slack) <br>
                Adrien Bouet (Gale sur slack) <br>
                Salomé d'Audeteau (Fihiz sur slack)<br>
                Caen, 14000
              </p>  
            </div>
          </div>

          <div class="col-md-6 widget">
            <h3 class="widget-title">NOTE AUX VISITEURS</h3>
            <div class="widget-body">
              <p>On ne vit qu'une fois. YOLO<br>
              “On n'a jamais rien à gagner à tenter de créer soi-même un événement. L'événement c'est comme la plomberie, une affaire de spécialiste.”
            De Daniel Schneidermann / Où sont les caméras </p>
            </div>
          </div>

        </div> <!-- /row of widgets -->
      </div>
    </div>

    <div class="footer2">
      <div class="container">
        <div class="row">
          

          <div class="col-md-6 widget">
            <div class="widget-body">
              <p class="text-right">
                Copyright &copy; 2019, Team Caen. Made with <i class="fas fa-heart"></i> from Caen.
              </p>
            </div>
          </div>

        </div> <!-- /row of widgets -->
      </div>
    </div>

  </footer> 

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip();
    $(".dropdown-toggle").dropdown();
  })
</script>
  </body>
</html>

EventBrite-master/app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
  	 <title>EvenbriteProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <link href="https://bootswatch.com/4/lux/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">EVENT AFTER ALL</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to "CRÉER UN EVENT", new_event_path, :class => "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          MON COMPTE
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Voir mon profil", current_user, :class => "dropdown-item" %>
          <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, :class => "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          S'INSCRIRE/SE CONNECTER
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Se connecter", new_user_session_path, :class => "dropdown-item" %>
          <%= link_to "S'inscrire", new_user_registration_path, :class => "dropdown-item" %>
        </div>
      </li>
      <% end %>

    </ul>
  </div>
</nav>
    <%= yield %>

    <p style="margin-bottom:45px;">

<article>
  <center><blockquote>
    <h4><em>"Le courage, le vrai, ça n'est pas d'attendre avec calme l'événement ; c'est de courir au devant, pour le connaître le plus tôt possible, et l'accepter."</em></h4>
</blockquote>

<cite><strong>Roger Martin Du Gard</strong></cite></center>
</article>

<p style="margin-bottom:150px;">

<center><div class="container">
   <!-- Example row of columns -->
   <div class="row">
     <div class="col-md-4">
       <p><i class="fab fa-angellist"></i></br>
        <p style="margin-bottom:50px;">
        <h3><strong>Performant</strong></h3>
       Un superbe site d'events.</p>
     </div>
     <div class="col-md-4">
      <i class="fas fa-american-sign-language-interpreting"></i>
      <p style="margin-bottom:50px;">
       <h3><strong>Sécurisé</strong></h3>
       <p>Payez en toute sécurité avec notre système THP SECURE.</p>
     </div>
     <div class="col-md-4">
      <i class="fas fa-award"></i>
      <p style="margin-bottom:50px;">
       <h3><strong>Ingénieux</strong></h3>
       <p>En fait, on n'est pas encore sûrs de tout.</p>
     </div>
   </div></center>
 <p style="margin-bottom:150px;">

      <footer id="footer" class="top-space">

    <div class="footer1">
      <div class="container">
        <div class="row">
          
          <div class="col-md-3 widget">
            <h3 class="widget-title">Contact</h3>
            <div class="widget-body">
              <p>On est sur le Slack!<br>
                Jonathan Gaultier (Joongau sur slack) <br>
                Rémi Auzou (pas de pseudo pour monsieur) <br>
                Dylan Langlois-Hérault (Dylan LH sur slack) <br>
                Cyrille Amaro (Howok sur slack) <br>
                Armand Duval (Urbain4 sur slack) <br>
                Adrien Bouet (Gale sur slack) <br>
                Salomé d'Audeteau (Fihiz sur slack)<br>
                Caen, 14000
              </p>  
            </div>
          </div>

          <div class="col-md-6 widget">
            <h3 class="widget-title">NOTE AUX VISITEURS</h3>
            <div class="widget-body">
              <p>On ne vit qu'une fois. YOLO<br>
              “On n'a jamais rien à gagner à tenter de créer soi-même un événement. L'événement c'est comme la plomberie, une affaire de spécialiste.”
            De Daniel Schneidermann / Où sont les caméras </p>
            </div>
          </div>

        </div> <!-- /row of widgets -->
      </div>
    </div>

    <div class="footer2">
      <div class="container">
        <div class="row">
          

          <div class="col-md-6 widget">
            <div class="widget-body">
              <p class="text-right">
                Copyright &copy; 2019, Team Caen. Made with <i class="fas fa-heart"></i> from Caen.
              </p>
            </div>
          </div>

        </div> <!-- /row of widgets -->
      </div>
    </div>

  </footer> 

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip();
    $(".dropdown-toggle").dropdown();
  })
</script>
  </body>
</html>

EventBrite-master/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

EventBrite-master/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

EventBrite-master/app/views/users/show.html.erb
<h1>Salut <%= @user.email %> !</h1>

	<!-- Intro -->
	<div class="container text-center">
		<br> <br>
		<h2 class="thin">Voici ta page utilisateur</h2>
		<p class="text-muted">
			On n'est pas encore tout à fait au point, mais ça ne saurait tarder.<br> 
			tout vient à point.
		</p>
	</div>